-- Add new values to ViralCategory enum
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'TECHNOLOGY';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'HEALTH';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'BUSINESS';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'ENTERTAINMENT';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'SCIENCE';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'SPORTS';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'COOKING';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'MUSIC';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'TRAVEL';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'FINANCE';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'MOTIVATION';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'COMEDY';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'GAMING';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'FASHION';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'DIY';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'POLITICS';
ALTER TYPE "ViralCategory" ADD VALUE IF NOT EXISTS 'ENVIRONMENT';

-- Add new columns to viral_content_processing
ALTER TABLE "viral_content_processing" ADD COLUMN IF NOT EXISTS "tone" TEXT;
ALTER TABLE "viral_content_processing" ADD COLUMN IF NOT EXISTS "target_audience" TEXT;
ALTER TABLE "viral_content_processing" ADD COLUMN IF NOT EXISTS "content_goal" TEXT DEFAULT 'COURSE';
ALTER TABLE "viral_content_processing" ADD COLUMN IF NOT EXISTS "generated_file_path" TEXT;
ALTER TABLE "viral_content_processing" ADD COLUMN IF NOT EXISTS "auto_publish_youtube" BOOLEAN NOT NULL DEFAULT false;
