// @courseforge/db — Shared Zod schemas and TypeScript types.
// Prisma client lives in backend/. This package provides shared types and validation.

export type {
  // Enum types
  UserRole,
  CourseStatus,
  ModuleStatus,
  VideoJobStatus,
  VoiceMode,
  AvatarProvider,
  SlideStyle,
  PublicationStatus,
  AgentScope,
  AgentType,
  AgentTone,
  ChatMessageRole,
  DiscountType,
  HeatmapEventType,
  // Row types
  User,
  CreatorProfile,
  StudentProfile,
  Category,
  Course,
  CourseModule,
  VideoJob,
  GenerationConfig,
  Purchase,
  Enrollment,
  ModuleProgress,
  AgentConfig,
  Certificate,
  Coupon,
  AffiliateLink,
  PaginatedResponse,
} from './types';

export {
  // Enum schemas
  UserRoleSchema,
  CourseStatusSchema,
  ModuleStatusSchema,
  VideoJobStatusSchema,
  VoiceModeSchema,
  AvatarProviderSchema,
  SlideStyleSchema,
  PublicationStatusSchema,
  AgentScopeSchema,
  AgentTypeSchema,
  AgentToneSchema,
  ChatMessageRoleSchema,
  DiscountTypeSchema,
  HeatmapEventTypeSchema,
  // Validation schemas
  CreateUserSchema,
  UpdateUserSchema,
  UpdateCreatorProfileSchema,
  UpdateStudentProfileSchema,
  CreateCategorySchema,
  UpdateCategorySchema,
  CreateCourseSchema,
  UpdateCourseSchema,
  CreateCourseModuleSchema,
  UpdateCourseModuleSchema,
  CreateGenerationConfigSchema,
  CreatePurchaseSchema,
  CreateEnrollmentSchema,
  UpsertModuleProgressSchema,
  CreateAgentConfigSchema,
  UpdateAgentConfigSchema,
  CreateChatMessageSchema,
  CreateAffiliateLinkSchema,
  CreateCouponSchema,
  UpdateCouponSchema,
  CreateEmailSubscriberSchema,
  CreateCertificateSchema,
  CreateVideoHeatmapEventSchema,
} from './schemas';

export type {
  CreateUser,
  UpdateUser,
  CreateCategory,
  UpdateCategory,
  CreateCourse,
  UpdateCourse,
  CreateCourseModule,
  UpdateCourseModule,
  CreateGenerationConfig,
  CreatePurchase,
  CreateEnrollment,
  UpsertModuleProgress,
  CreateAgentConfig,
  UpdateAgentConfig,
  CreateChatMessage,
  CreateAffiliateLink,
  CreateCoupon,
  UpdateCoupon,
  CreateEmailSubscriber,
  CreateCertificate,
  CreateVideoHeatmapEvent,
} from './schemas';
